<a href="https://colab.research.google.com/github/Mtaimoorakmal/Python/blob/main/numpyTut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Array

In [28]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr.shape) # show the dimensions of teh array
print(arr.size)
print(arr.dtype)

(5,)
5
int64


In [55]:
print(np.__version__)

1.25.2


list and Tuple both can be passsed to have a numpy array

In [59]:
arr1 = np.array((1, 2, 3, 4, 5)) # tuple passed
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Multidimentinal Array

In [79]:
# O-D array
arr_0 = np.array(32)
print(arr_0) #output 32
print(arr_0.ndim) # output 0
print(arr_0.shape) #output ()
# 1-D array
print("1-D array: has 0-D array as elements")
arr_1 = np.array([1,2,3])
print(arr_1) #output [1,2,3]
print(arr_1.ndim) # output 1
print(arr_1.shape) #output (3,)

# 2-D array
print("2-D array: has 1-D array as elements")
arr_2 = np.array([[1,2,3] , [7,8,9]])
print(arr_2) #output [[1 2 3]
#                     [7 8 9]]
print(arr_2.ndim) # output 2
print(arr_2.shape) #output (2,3)

# 3-D array
print("3-D array: has 2-D array as elements")
arr_3 = np.array([[[1,2,3] , [7,8,9]],[[1,2,3,] ,[7,8,9]]])
print(arr_3)
print(arr_3.ndim) # output 3
print(arr_3.shape) # output (2,2,3)


32
()
0
1-D array: has 0-D array as elements
[1 2 3]
(3,)
1
2-D array: has 1-D array as elements
[[1 2 3]
 [7 8 9]]
(2, 3)
2
3-D array: has 2-D array as elements
[[[1 2 3]
  [7 8 9]]

 [[1 2 3]
  [7 8 9]]]
(2, 2, 3)
3


In [46]:
list_a = [[1,2,3,2] , [2,4,5,6],[2,0,9,8],[1,0,1,0]]
arr2 = np.array(list_a)
print(arr2.shape)
print(arr2.size)

(4, 4)
16


# functions
no.arange(strat , stop , jump)

In [54]:
arr = np.arange(100,10,-10)
print(arr)
print(type(arr))

[100  90  80  70  60  50  40  30  20]
<class 'numpy.ndarray'>
